version: '2'
services:
  factorio:
    build: .
    ports:
     - "34197:34197/udp"
     - "27015:27015/tcp"
    volumes:
     - /opt/factorio:/factorio
    environment:
     - UPDATE_MODS_ON_START=true
#    user: 845:845
#    user: 1000:1000
